# Generated by Django 2.1.1 on 2018-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_auto_20181001_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('folder_count', models.IntegerField()),
                ('file_count', models.IntegerField()),
                ('total_size', models.BigIntegerField()),
            ],
        ),
    ]
