# Generated by Django 2.1.1 on 2018-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_updatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelog',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
