# Generated by Django 2.1.1 on 2019-06-04 23:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=32, null=True)),
                ('date_created', models.DateTimeField()),
                ('directory_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('total_size', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('total_size', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('date_scanned', models.DateTimeField()),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('root_path', models.CharField(blank=True, max_length=512)),
                ('folder_count', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('has_checksums', models.BooleanField(default=True)),
                ('total_size', models.BigIntegerField(default=0)),
                ('size_timeline_data', models.TextField(blank=True, null=True)),
                ('type_chart_data', models.TextField(blank=True, null=True)),
                ('directory_type', models.CharField(choices=[('iRODS', 'iRODS'), ('CyVerse', 'CyVerse'), ('Local folder', 'Local folder')], default='Local folder', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_data.Folder'),
        ),
        migrations.AddField(
            model_name='filetype',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_data.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_data.Folder'),
        ),
    ]
