# Generated by Django 2.1.1 on 2019-07-11 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=32, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField()),
                ('date_accessed', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=32)),
                ('owner', models.CharField(blank=True, max_length=32, null=True)),
                ('group', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('total_size', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('total_size', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('date_scanned', models.DateTimeField()),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('root_path', models.CharField(blank=True, max_length=512)),
                ('folder_count', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('has_checksums', models.BooleanField(default=True)),
                ('has_owners', models.BooleanField(default=False)),
                ('has_access_times', models.BooleanField(default=False)),
                ('has_creation_times', models.BooleanField(default=False)),
                ('total_size', models.BigIntegerField(default=0)),
                ('size_timeline_data', models.TextField(blank=True, null=True)),
                ('type_chart_data', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('iRODS', 'iRODS'), ('CyVerse', 'CyVerse'), ('S3', 'S3'), ('Local folder', 'Local folder')], default='Local folder', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('total_size', models.BigIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.FileSource')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('total_size', models.BigIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_data.Folder')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.FileSource')),
            ],
        ),
        migrations.AddField(
            model_name='fileowner',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.FileSource'),
        ),
        migrations.AddField(
            model_name='filegroup',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.FileSource'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_data.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_data.Folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_data.FileSource'),
        ),
    ]
