# Generated by Django 2.1.1 on 2018-11-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('folder_count', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
            ],
        ),
    ]
