# Generated by Django 2.1.1 on 2019-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupegroup',
            name='directory',
        ),
        migrations.AddField(
            model_name='dupegroup',
            name='directories',
            field=models.ManyToManyField(to='file_data.ImportedDirectory'),
        ),
    ]
