# Generated by Django 2.1.1 on 2019-02-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0002_auto_20190107_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='extension',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
