# Generated by Django 2.1.1 on 2019-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0002_auto_20190405_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupegroup',
            name='directories',
        ),
        migrations.RemoveField(
            model_name='file',
            name='dupe_group',
        ),
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='DupeGroup',
        ),
    ]
