# Generated by Django 2.1.1 on 2018-12-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0002_filesummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetype',
            old_name='extension_pattern',
            new_name='extension',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='name',
        ),
    ]
