# Generated by Django 2.1.1 on 2019-03-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0003_auto_20190215_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesummary',
            name='top_folder',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
