# Generated by Django 2.1.1 on 2019-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0003_auto_20190408_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddirectory',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
