# Generated by Django 2.1.1 on 2019-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0004_filesummary_top_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesummary',
            old_name='timestamp',
            new_name='date_scanned',
        ),
    ]
