# Generated by Django 2.1.1 on 2019-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0004_importeddirectory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='directory_name',
            field=models.CharField(default='SOBS', max_length=32),
            preserve_default=False,
        ),
    ]
