# Generated by Django 2.1.1 on 2019-03-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0005_auto_20190314_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesummary',
            old_name='top_folder',
            new_name='root_path',
        ),
    ]
