# Generated by Django 2.1.1 on 2019-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0005_file_directory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddirectory',
            name='date_scanned',
            field=models.DateTimeField(),
        ),
    ]
