# Generated by Django 2.1.1 on 2019-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0006_auto_20190314_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('root_path', models.CharField(blank=True, max_length=512)),
                ('folder_count', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('size_timeline_data', models.TextField(blank=True, null=True)),
                ('type_chart_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FileSummary',
        ),
    ]
