# Generated by Django 2.1.1 on 2019-03-18 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0007_auto_20190318_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupegroup',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
        migrations.AddField(
            model_name='filetype',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
        migrations.AddField(
            model_name='folder',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_data.ImportedDirectory'),
        ),
    ]
