# Generated by Django 2.1.1 on 2019-03-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0008_auto_20190318_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddirectory',
            name='directory_type',
            field=models.CharField(choices=[('iRODS', 'iRODS'), ('CyVerse', 'CyVerse'), ('Local folder', 'Local folder')], default='Local folder', max_length=16),
        ),
    ]
