# Generated by Django 2.1.1 on 2018-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_updatelog_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
