# Generated by Django 2.1.1 on 2018-10-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_updatelog_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatelog',
            old_name='success',
            new_name='failed',
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
