# Generated by Django 2.1.1 on 2018-10-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181012_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.CharField(default='s8dj37rheuskdhsuc7483hru475hwy23', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
