# Generated by Django 2.1.1 on 2019-04-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_imported', models.DateTimeField(auto_now_add=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('current_step', models.IntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('irods_host', models.CharField(blank=True, default='data.cyverse.org', max_length=64)),
                ('irods_port', models.CharField(blank=True, default='1247', max_length=64)),
                ('root_path', models.CharField(blank=True, max_length=512)),
                ('irods_zone', models.CharField(blank=True, default='iplant', max_length=64)),
                ('import_method', models.CharField(blank=True, choices=[('iRODS', 'iRODS'), ('CyVerse', 'CyVerse'), ('File', 'File')], default='File', max_length=1)),
            ],
        ),
    ]
