# Generated by Django 2.1.1 on 2018-12-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_progress', models.BooleanField(default=True)),
                ('current_step', models.IntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('irods_user', models.CharField(blank=True, max_length=64)),
                ('irods_host', models.CharField(blank=True, max_length=64)),
                ('irods_port', models.CharField(blank=True, max_length=64)),
                ('irods_zone', models.CharField(blank=True, max_length=64)),
                ('top_folder', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
