# Generated by Django 2.1.1 on 2019-07-11 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('status_message', models.CharField(blank=True, max_length=128)),
                ('status_subtitle', models.CharField(blank=True, max_length=128)),
                ('failed', models.BooleanField(default=False)),
                ('warning', models.BooleanField(default=False)),
                ('fixture', models.FileField(blank=True, null=True, upload_to='fixtures/')),
            ],
        ),
        migrations.CreateModel(
            name='ImportAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_imported', models.DateTimeField(auto_now_add=True)),
                ('irods_user', models.CharField(blank=True, max_length=64)),
                ('irods_host', models.CharField(blank=True, default='data.cyverse.org', max_length=64)),
                ('irods_port', models.CharField(blank=True, default='1247', max_length=64)),
                ('irods_zone', models.CharField(blank=True, default='iplant', max_length=64)),
                ('irods_root', models.CharField(blank=True, max_length=512)),
                ('irods_name', models.CharField(blank=True, default='My iRODS Files', max_length=32)),
                ('cyverse_user', models.CharField(blank=True, max_length=64)),
                ('cyverse_root', models.CharField(blank=True, max_length=512)),
                ('cyverse_name', models.CharField(blank=True, default='My CyVerse Files', max_length=32)),
                ('s3_key', models.CharField(blank=True, max_length=64)),
                ('s3_bucket', models.CharField(blank=True, max_length=64)),
                ('s3_root', models.CharField(blank=True, max_length=512)),
                ('s3_name', models.CharField(blank=True, default='My S3 Files', max_length=32)),
                ('file_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='asynctask',
            name='import_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='importer.ImportAttempt'),
        ),
    ]
