# Generated by Django 2.1.1 on 2019-02-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importattempt',
            old_name='irods_user',
            new_name='username',
        ),
    ]
