# Generated by Django 2.1.1 on 2018-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelog',
            name='irods_host',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='irods_port',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='irods_user',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='irods_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='top_folder',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
