# Generated by Django 2.1.1 on 2018-11-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20181119_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatelog',
            name='file',
        ),
    ]
