# Generated by Django 2.1.1 on 2019-04-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20190408_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='importattempt',
            name='source_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
