# Generated by Django 2.1.1 on 2019-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_importattempt_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importattempt',
            name='root_path',
        ),
        migrations.RemoveField(
            model_name='importattempt',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='importattempt',
            name='username',
        ),
        migrations.AddField(
            model_name='importattempt',
            name='cyverse_name',
            field=models.CharField(blank=True, default='My CyVerse Files', max_length=32),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='cyverse_root',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='cyverse_user',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='file_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='irods_name',
            field=models.CharField(blank=True, default='My iRODS Files', max_length=32),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='irods_root',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='irods_user',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='s3_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='s3_name',
            field=models.CharField(blank=True, default='My S3 Files', max_length=32),
        ),
        migrations.AddField(
            model_name='importattempt',
            name='s3_root',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
