# Generated by Django 2.1.1 on 2019-03-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_auto_20190215_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132)),
                ('db_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='importattempt',
            old_name='timestamp',
            new_name='date_imported',
        ),
        migrations.RenameField(
            model_name='importattempt',
            old_name='top_folder',
            new_name='root_path',
        ),
        migrations.AddField(
            model_name='importeddirectory',
            name='import_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.ImportAttempt'),
        ),
    ]
