# Generated by Django 2.1.1 on 2019-04-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20190423_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importattempt',
            name='import_method',
        ),
    ]
