# Generated by Django 2.1.1 on 2019-03-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20190314_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importeddirectory',
            name='import_attempt',
        ),
        migrations.AddField(
            model_name='importattempt',
            name='import_method',
            field=models.CharField(blank=True, choices=[('i', 'iRODS'), ('c', 'CyVerse'), ('f', 'File')], max_length=1),
        ),
        migrations.DeleteModel(
            name='ImportedDirectory',
        ),
    ]
