# Generated by Django 2.1.1 on 2019-03-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_auto_20190318_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importattempt',
            name='import_method',
            field=models.CharField(blank=True, choices=[('iRODS', 'iRODS'), ('CyVerse', 'CyVerse'), ('File', 'File')], default='File', max_length=1),
        ),
    ]
