# Generated by Django 2.1.1 on 2019-04-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_remove_importattempt_import_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('status_message', models.CharField(blank=True, max_length=128)),
                ('status_subtitle', models.CharField(blank=True, max_length=128)),
                ('failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='importattempt',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='importattempt',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='importattempt',
            name='in_progress',
        ),
        migrations.AddField(
            model_name='asynctask',
            name='import_attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='importer.ImportAttempt'),
        ),
    ]
