# Generated by Django 2.1.1 on 2019-05-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_auto_20190430_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='import_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='importer.ImportAttempt'),
        ),
    ]
