# Generated by Django 2.1.1 on 2019-06-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_asynctask_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
